In [1]:
import torch

/home/kara4/anaconda3/envs/foundationsense/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
def generate_alternating_bitmask(size=(128, 4, 8)):
    bit_mask = torch.zeros(size, dtype=torch.bool)
    
    # Set alternating columns to True
    bit_mask[:, :, ::2] = True
    
    return bit_mask

bit_mask = generate_alternating_bitmask()
print(bit_mask.shape)
print(bit_mask)


torch.Size([128, 4, 8])
tensor([[[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        ...,

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[

In [7]:
import torch

def generate_alternating_bitmask(size=(128, 4, 8)):
    bit_mask = torch.zeros(size, dtype=torch.bool)

    # Randomly choose between alternating rows and alternating columns
    choice = torch.randint(0, 2, (1,))

    if choice == 0:
        # Set alternating columns to True
        bit_mask[:, :, ::2] = True
    else:
        # Set alternating rows to True
        bit_mask[:, ::2, :] = True
    
    return bit_mask


torch.Size([128, 4, 8])
tensor([[[ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        [[ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        ...,

        [[ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False],
         [ True,  True,  True,  ...,  True,  True,  True],
         [False, False, False,  ..., False, False, False]],

        [[

In [9]:
bit_mask = generate_alternating_bitmask()
print(bit_mask.shape)
print(bit_mask)


torch.Size([128, 4, 8])
tensor([[[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        ...,

        [[ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False],
         [ True, False,  True,  ..., False,  True, False]],

        [[